---
- name: Развёртывание Nginx в Docker
  hosts: demo
  become: true

  vars:
    nginx_host_dir: /opt/nginx
    nginx_container_name: nginx_web
    nginx_port: 8081

  tasks:
    - name: Создание директории для Nginx
      ansible.builtin.file:
        path: "{{ nginx_host_dir }}"
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Копирование файлов конфигурации
      block:
        - name: Копирование index.html
          ansible.builtin.copy:
            src: "{{ playbook_dir }}/index.html"
            dest: "{{ nginx_host_dir }}/index.html"
            owner: root
            group: root
            mode: 0644

        - name: Копирование nginx.conf
          ansible.builtin.copy:
            src: "{{ playbook_dir }}/nginx.conf"
            dest: "{{ nginx_host_dir }}/nginx.conf"
            owner: root
            group: root
            mode: 0644

    - name: Проверка существования контейнера
      community.docker.docker_container_info:
        name: "{{ nginx_container_name }}"
      register: container_info
      ignore_errors: yes
      changed_when: false

    - name: Удаление старого контейнера (если существует)
      community.docker.docker_container:
        name: "{{ nginx_container_name }}"
        state: absent
      when: container_info.exists | default(false)
      async: 45
      poll: 0

    - name: Ожидание завершения удаления (только если удаляли)
      async_status:
        jid: "{{ ansible_job_id }}"
      register: async_result
      until: async_result.finished
      retries: 15
      delay: 3
      when: container_info.exists | default(false)

    - name: Запуск и проверка Nginx
      block:
        - name: Запуск контейнера Nginx
          community.docker.docker_container:
            name: "{{ nginx_container_name }}"
            image: nginx:latest
            state: started
            restart_policy: always
            ports:
              - "{{ nginx_port }}:80"
            volumes:
              - "{{ nginx_host_dir }}/index.html:/usr/share/nginx/html/index.html:ro"
              - "{{ nginx_host_dir }}/nginx.conf:/etc/nginx/conf.d/default.conf:ro"

        - name: Ожидание запуска Nginx
          ansible.builtin.wait_for:
            port: "{{ nginx_port }}"
            host: localhost
            delay: 5
            timeout: 60

        - name: Проверка доступности Nginx
          ansible.builtin.uri:
            url: "http://localhost:{{ nginx_port }}"
            return_content: yes
            status_code: 200
            timeout: 30
          register: nginx_test

        - name: Вывод результата проверки
          ansible.builtin.debug:
            msg: "Nginx успешно запущен! Статус: {{ nginx_test.status }}"

      rescue:
        - name: Остановка проблемного контейнера
          community.docker.docker_container:
            name: "{{ nginx_container_name }}"
            state: absent
          ignore_errors: yes

        - name: Сообщение об ошибке
          ansible.builtin.fail:
            msg: "Не удалось запустить Nginx контейнер. Проверьте логи и конфигурацию."
