services:
  nginx:
    image: nginx:stable-alpine
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    configs:
      - source: config
        target: /etc/nginx/nginx.conf
    networks:
      - appnet
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_DB: mydb
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_password
    secrets:
      - source: pg_password
        target: pg_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - appnet
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          # запустить только на ноде с лейблом node.labels.pg == "true"
          - "node.labels.pg == true"

configs:
  config:
    external: false

secrets:
  pg_password:
    external: false

volumes:
  pgdata:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/srv/postgres/data"

networks:
  appnet:
    driver: overlay
    attachable: true
