---
- name: Сбор системной информации
  hosts: localhost
  gather_facts: yes
  tasks:
    - name: Сбор информации о системе
      setup:
        filter:
          - "ansible_hostname"
          - "ansible_os_family"
          - "ansible_distribution"
          - "ansible_distribution_version"
          - "ansible_default_ipv4"
          - "ansible_env"
      
    - name: Запись информации в файл
      copy:
        content: |
          === СИСТЕМНАЯ ИНФОРМАЦИЯ ===
          Hostname: {{ ansible_hostname }}
          Тип OS: {{ ansible_os_family }}
          Дистрибутив: {{ ansible_distribution }}
          Версия OS: {{ ansible_distribution_version }}
          IP-адрес: {{ ansible_default_ipv4.address }}
          
          === ПЕРЕМЕННЫЕ ОКРУЖЕНИЯ ===
          {% for key, value in ansible_env.items() %}
          {{ key }}: {{ value }}
          {% endfor %}
        dest: ./info.txt
