---
- name: Установка Docker
  hosts: demo
  become: true

  tasks:
    - block:
      - name: Зависимости
        ansible.builtin.apt:
          name:
            - ca-certificates
            - curl
          update-cache: yes
          cache_valid_time: 86400

      - name: Ключи
        ansible.builtin.apt_key:
          url: https://download.docker.com/linux/ubuntu/gpg
          keyring: /etc/apt/keyrings/docker.asc
          state: present

      - name: Установка стабильного репозитория
        ansible.builtin.apt_repository:
          repo: >
            deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc]
            https://download.docker.com/linux/ubuntu/ {{ ansible_distribution_release }} stable
          state: present
          update-cache: yes
          filename: docker

      - name: Установка Docker
        ansible.builtin.apt:
          name:
            - docker-ce
            - docker-ce-cli
            - containerd.io
            - docker-buildx-plugin
            - docker-compose-plugin
          update-cache: yes

      - name: Проверка что докер установлен и перезагружен
        ansible.builtin.service:
          name: docker
          state: started
          enabled: yes

      - name: Завершение установки
        block:
          - name: Создание группы docker
            ansible.builtin.group:
              name: docker
              state: present

          - name: Добавление пользователя в группу docker
            ansible.builtin.user:
              name: "{{ ansible_user }}"
              groups: docker
              append: yes

          - name: Перезагрузка
            ansible.builtin.reboot:
              reboot_timeout: 0

        when: ansible_facts['distribution'] == 'Ubuntu'

      when: ansible_facts['distribution'] == 'Ubuntu'
